import { initPlayer } from './script/player';
import { ticketsAmount } from './script/tickets_amount';
import { updateGallery } from './script/gallery';
import { showOverlay } from './script/overlay';
import { map } from './script/map';
import { ripleEffect } from './script/riple_effect';
import { burger } from './script/burger';
import { findVideo } from './script/video-iframe';
import { sliderExplore } from './script/slider-explore';
import { welcomeSlider } from './script/welcome-slider';
import { fonMusic } from './script/fonMusic';
import { musicPlay, audio, video, videoStart } from './script/sharedConstants';
import { validate } from './script/validate';

import './style/style.scss';
import './style/video-player.scss';
import './style/gallery.scss';
import './style/tickets.scss';
import './style/contacts.scss';
import './style/footer.scss';
import './style/booking-tickets.scss';
import './style/burger.scss';
import './style/video-iframe.scss';

initPlayer();
ticketsAmount();
updateGallery();
showOverlay();
map();
ripleEffect();
burger();
findVideo();
sliderExplore();
welcomeSlider();
fonMusic();
validate();

console.log('1. Слайдер в секции Welcome +20 (слайды не перелистываются плавно с анимацией -4)');
console.log('2. Слайдер в секции Video +18 (слайды не перелистываются плавно с анимацией -2)');
console.log('3. Кастомный видеоплеер +36');
console.log('4. Слайдер сравнения изображений в секции Explore +10');
console.log('5. Анимация при прокрутке изображений в секции Galery +8');
console.log('6. Калькулятор продажи билетов в секции Tiskets +10');
console.log('7. Калькулятор продажи билетов в форме продажи билетов +14');
console.log('8. Валидация формы +16');
console.log('9. Интерактивная карта в секции Contacts +12');
console.log('10. Cобственный дополнительный функционал (добавлена дата и фоновая музыка, закрепленные в верху страницы) +10');
console.log('Итого: 154/160');
