import { initPlayer } from './script/player';
import { ticketsAmount } from './script/tickets_amount';
import { updateGallery } from './script/gallery';
import { showOverlay } from './script/overlay';
import { map } from './script/map';
import { ripleEffect } from './script/ripleEffect';
import { burger } from './script/burger';
import { findVideo } from './script/video-iframe';
import { sliderExplore } from './script/slider-explore';
import { welcomeSlider } from './script/welcome-slider';
import { fonMusic } from './script/fonMusic';
import { validate } from './script/validate';

import './style/style.scss';
import './style/video-player.scss';
import './style/gallery.scss';
import './style/tickets.scss';
import './style/contacts.scss';
import './style/footer.scss';
import './style/booking-tickets.scss';
import './style/burger.scss';
import './style/video-iframe.scss';

initPlayer();
ticketsAmount();
updateGallery();
showOverlay();
map();
ripleEffect();
burger();
findVideo();
sliderExplore();
welcomeSlider();
fonMusic();
validate();
